### ISSUE TITLE
Please center hero

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Russian#2]
Hey when you get a chance can you please center the hero? Thanks!

**Comment by CVE82** [comment]
@ZMcGroarty  Can you center and size the hero when you get a chance please? I will update with the new file =)

**Comment by ZMcGroarty** [comment]
I want to try something different for each of these. Im grabbing panoramic images from stock sites.

![russian](https://user-images.githubusercontent.com/15017242/43481718-b83586d8-94d4-11e8-984c-f206f449d9e3.png)
